name: changesets
on:
  push:
    branches: -master
jobs:
  changeset:
    if: github.repository == 'jnm2377/changeset-demo'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Create .npmrc file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > "$HOME/.npmrc"
          echo '@jnm2377:registry=https://npm.pkg.github.com/' >> "$HOME/.npmrc"
      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Scheduled release"
          commit: "chore(project): run changeset version"
          version: yarn changeset version
          publish: yarn changeset publish
